In [1]:
import pandas as pd

In [3]:
df= pd.read_csv(r"C:\Users\nikhi\projects\iot_ps\energy_dataset\all_buildings_power.csv")

In [4]:
df.head()

,timestamp,Academic,Boys_main,Boys_backup,Facilities,Girls_main,Girls_backup,Lecture,Library,Mess
0,1.376073e+09,28368.60645,28298.05859,11521.14258,NaN,9817.66846,6324.17847,0.0,3972.19702,NaN
1,1.376073e+09,28411.98828,28327.11426,11532.83105,NaN,9804.43408,6348.66260,0.0,3972.83789,NaN
2,1.376073e+09,28752.53809,28343.01562,11538.75635,NaN,9834.51758,6384.14258,0.0,3974.43042,NaN
3,1.376073e+09,29031.44629,28447.11719,11879.18115,NaN,9881.32666,6404.63501,0.0,3981.96484,NaN
4,1.376073e+09,28487.45801,28393.62207,12565.78662,NaN,9894.75684,6434.62622,0.0,3986.44995,NaN

In [5]:
df.describe()

,timestamp,Academic,Boys_main,Boys_backup,Facilities,Girls_main,Girls_backup,Lecture,Library,Mess
count,2.310568e+06,2.269527e+06,1.671544e+06,1.688043e+06,2.048903e+06,1.653053e+06,2.300745e+06,2.269309e+06,1.713637e+06,2.013089e+06
mean,1.445394e+09,2.778582e+04,1.748801e+04,1.392737e+04,1.045892e+04,7.315914e+03,6.881255e+03,6.416937e+02,9.074730e+03,2.219535e+04
std,4.002673e+07,1.401836e+04,8.375309e+03,5.152703e+03,4.673187e+03,2.658483e+03,2.116446e+03,1.552832e+03,6.655733e+03,8.822726e+03
min,1.376073e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.324592e+02
25%,1.410732e+09,1.813406e+04,1.151557e+04,1.001611e+04,8.073814e+03,5.314344e+03,5.312342e+03,0.000000e+00,4.483057e+03,1.556387e+04
50%,1.445390e+09,2.334184e+04,1.559360e+04,1.306873e+04,9.860552e+03,7.079641e+03,6.782574e+03,0.000000e+00,6.710730e+03,2.064835e+04
75%,1.480049e+09,3.324996e+04,2.150550e+04,1.729778e+04,1.230265e+04,8.994355e+03,8.319595e+03,0.000000e+00,1.153799e+04,2.734457e+04
max,1.514745e+09,9.578633e+04,9.766386e+04,4.721214e+04,1.394371e+05,2.089592e+04,1.812682e+04,2.670307e+04,9.920895e+04,1.424421e+05

In [6]:
df.isnull().sum()

timestamp            0
Academic         41041
Boys_main       639024
Boys_backup     622525
Facilities      261665
Girls_main      657515
Girls_backup      9823
Lecture          41259
Library         596931
Mess            297479
dtype: int64

In [8]:
df.notnull().sum()

timestamp       2310568
Academic        2269527
Boys_main       1671544
Boys_backup     1688043
Facilities      2048903
Girls_main      1653053
Girls_backup    2300745
Lecture         2269309
Library         1713637
Mess            2013089
dtype: int64